### ISSUE TITLE
Undefined method dark?

### ISSUE THREAD

**Issue by jtFrancisco** [DCarper/rqrcode_png#16]
I get the following error:
`undefined method `dark?' for #<RQRCode::QRCode:0x00007ff80f249078>`

When I do this:
`<%= image_tag RQRCode::QRCode.new(organization.uuid.to_s).to_img.to_data_url %>`

**Comment by madoleary** [comment]
I'm getting the same error. It's happening when to_img is called on the QR code instance.

Update: I can't find a method named "dark?" defined anywhere in the source code. Perhaps this is a related issue: https://github.com/whomwah/rqrcode/issues/75

**Comment by lazlyhu** [comment]
@donBigote @madoleary It's fixed here: https://github.com/DCarper/rqrcode_png/pull/15
If you pull your branch from there or the current master it should working fine. The `rubygems` version not updated yet :/

**Comment by bylaxdee** [comment]
`gem 'rqrcode_png', git: "https://github.com/DCarper/rqrcode_png.git"`  :smile:
